### ISSUE TITLE
[ThreadDump]複数ブラウザから同時にスレッドダンプ取得ボタンが押された場合に、WGPRuntimeExceptionが発生する場合がある。

### ISSUE THREAD

**Issue by miyasakago** [endosnipe/ENdoSnipe#568]
■動作環境 (Environment)
 ENdoSnipe Agent Ver.5.1.0
 Apache Tomcat/7.0.29
 Windows7

【1.現象 (Fact)】
 複数ブラウザから同時にスレッドダンプ取得ボタンが押された場合に、WGPRuntimeExceptionが発生する場合がある。
 
 Errorログは以下の通り。
 =========================================================================
 org.wgp.exception.WGPRuntimeException
	at org.wgp.manager.WgpBufferManager.setChangeData(WgpBufferManager.java:113)
	at org.wgp.interceptor.ChangeDataInterceptor.addInterceptor(ChangeDataInterceptor.java:71)
	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:603)
	at org.springframework.aop.aspectj.AspectJMethodBeforeAdvice.before(AspectJMethodBeforeAdvice.java:39)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:49)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621)
	at org.wgp.manager.WgpDataManager$$EnhancerByCGLIB$$2bf545ef.setData(<generated>)
	at jp.co.acroquest.endosnipe.web.explorer.listener.collector.AlarmThreadDumpNotifyListener.doReceiveTelegram(AlarmThreadDumpNotifyListener.java:57)
	at jp.co.acroquest.endosnipe.communicator.AbstractTelegramListener.receiveTelegram(AbstractTelegramListener.java:52)
	at jp.co.acroquest.endosnipe.communicator.impl.TelegramReader.mainLoop(TelegramReader.java:221)
	at jp.co.acroquest.endosnipe.communicator.impl.TelegramReader.run(TelegramReader.java:151)
	at java.lang.Thread.run(Unknown Source)
 =========================================================================

【2.再現手順 (Operations)】
 複数のブラウザを立ち上げ、各ブラウザで同時にスレッドダンプ取得を行う。

【3.期待結果 (Expected result)】
 WGPRuntimeExceptionが発生しない。

【4.原因（reason）】
#629と同件。
2連続で同じキーのデータを送信したときに、WGP側で例外として扱っていた。

**Comment by s-fujii200** [comment]
対応完了したため、クローズする。
